export PYTHONPATH=/Users/mingyeongho/Desktop/연구실/lerobot/src:$PYTHONPATH


lerobot-record \
  --robot.type=so101_follower \
  --robot.port=/dev/tty.usbmodem5AAF2641771 \
  --robot.cameras="{ front: {type: opencv, index_or_path: 0, width: 640, height: 480, fps: 30}, top: {type: opencv, index_or_path: 1, width: 640, height: 480, fps: 30} }" \
  --robot.id=follower \
  --dataset.single_task="Grab the blue block and put in the cup" \
  --policy.repo_id=vlasil/pi0_policy_pen_1101



  # --pretrained_name_or_path=vlasil/pi0_policy_pen_1101 \




#  [--robot.type {so100_follower,bi_so100_follower,hope_jr_hand,hope_jr_arm,koch_follower,so101_follower}]
#                       [--robot.left_arm_port str] [--robot.right_arm_port str] [--robot.left_arm_disable_torque_on_disconnect str]
#                       [--robot.left_arm_max_relative_target str] [--robot.left_arm_use_degrees str]
#                       [--robot.right_arm_disable_torque_on_disconnect str] [--robot.right_arm_max_relative_target str]
#                       [--robot.right_arm_use_degrees str] [--robot.side str] [--robot.id str] [--robot.calibration_dir str] [--robot.port str]
#                       [--robot.disable_torque_on_disconnect str] [--robot.max_relative_target str] [--robot.cameras str]
#                       [--robot.use_degrees str] [--dataset str] [--dataset.repo_id str] [--dataset.single_task str] [--dataset.root str]
#                       [--dataset.fps str] [--dataset.episode_time_s str] [--dataset.reset_time_s str] [--dataset.num_episodes str]
#                       [--dataset.video str] [--dataset.push_to_hub str] [--dataset.private str] [--dataset.tags str]
#                       [--dataset.num_image_writer_processes str] [--dataset.num_image_writer_threads_per_camera str]
#                       [--dataset.video_encoding_batch_size str] [--dataset.rename_map str] [--teleop str]
#                       [--teleop.type {so100_leader,bi_so100_leader,homunculus_glove,homunculus_arm,koch_leader,so101_leader,keyboard,keyboard_ee}]
#                       [--teleop.left_arm_port str] [--teleop.right_arm_port str] [--teleop.side str] [--teleop.baud_rate str]
#                       [--teleop.gripper_open_pos str] [--teleop.port str] [--teleop.use_degrees str] [--teleop.id str]
#                       [--teleop.calibration_dir str] [--teleop.use_gripper str] [--policy str]
#                       [--policy.type {act,diffusion,groot,pi0,pi05,smolvla,tdmpc,vqbet,sac,reward_classifier}]
#                       [--policy.replace_final_stride_with_dilation str] [--policy.pre_norm str] [--policy.dim_model str] [--policy.n_heads str]
#                       [--policy.dim_feedforward str] [--policy.feedforward_activation str] [--policy.n_encoder_layers str]
#                       [--policy.n_decoder_layers str] [--policy.use_vae str] [--policy.n_vae_encoder_layers str]
#                       [--policy.temporal_ensemble_coeff str] [--policy.kl_weight str] [--policy.optimizer_lr_backbone str]
#                       [--policy.drop_n_last_frames str] [--policy.use_separate_rgb_encoder_per_camera str] [--policy.down_dims str]
#                       [--policy.kernel_size str] [--policy.n_groups str] [--policy.diffusion_step_embed_dim str]
#                       [--policy.use_film_scale_modulation str] [--policy.noise_scheduler_type str] [--policy.num_train_timesteps str]
#                       [--policy.beta_schedule str] [--policy.beta_start str] [--policy.beta_end str] [--policy.prediction_type str]
#                       [--policy.clip_sample str] [--policy.clip_sample_range str] [--policy.do_mask_loss_for_padding str]
#                       [--policy.scheduler_name str] [--policy.image_size str] [--policy.base_model_path str]
#                       [--policy.tokenizer_assets_repo str] [--policy.embodiment_tag str] [--policy.tune_llm str] [--policy.tune_visual str]
#                       [--policy.tune_projector str] [--policy.tune_diffusion_model str] [--policy.lora_rank str] [--policy.lora_alpha str]
#                       [--policy.lora_dropout str] [--policy.lora_full_model str] [--policy.warmup_ratio str] [--policy.use_bf16 str]
#                       [--policy.video_backend str] [--policy.balance_dataset_weights str] [--policy.balance_trajectory_weights str]
#                       [--policy.dataset_paths str] [--policy.output_dir str] [--policy.save_steps str] [--policy.max_steps str]
#                       [--policy.batch_size str] [--policy.dataloader_num_workers str] [--policy.report_to str] [--policy.resume str]
#                       [--policy.paligemma_variant str] [--policy.action_expert_variant str] [--policy.dtype str]
#                       [--policy.num_inference_steps str] [--policy.time_sampling_beta_alpha str] [--policy.time_sampling_beta_beta str]
#                       [--policy.time_sampling_scale str] [--policy.time_sampling_offset str] [--policy.image_resolution str]
#                       [--policy.gradient_checkpointing str] [--policy.compile_model str] [--policy.compile_mode str] [--policy.chunk_size str]
#                       [--policy.max_state_dim str] [--policy.max_action_dim str] [--policy.resize_imgs_with_padding str]
#                       [--policy.empty_cameras str] [--policy.adapt_to_pi_aloha str] [--policy.use_delta_joint_actions_aloha str]
#                       [--policy.tokenizer_max_length str] [--policy.num_steps str] [--policy.use_cache str] [--policy.train_expert_only str]
#                       [--policy.train_state_proj str] [--policy.optimizer_grad_clip_norm str] [--policy.scheduler_decay_steps str]
#                       [--policy.scheduler_decay_lr str] [--policy.vlm_model_name str] [--policy.load_vlm_weights str]
#                       [--policy.add_image_special_tokens str] [--policy.attention_mode str] [--policy.prefix_length str]
#                       [--policy.pad_language_to str] [--policy.num_expert_layers str] [--policy.num_vlm_layers str]
#                       [--policy.self_attn_every_n_layers str] [--policy.expert_width_multiplier str] [--policy.min_period str]
#                       [--policy.max_period str] [--policy.n_action_repeats str] [--policy.horizon str] [--policy.n_action_steps str]
#                       [--policy.q_ensemble_size str] [--policy.mlp_dim str] [--policy.use_mpc str] [--policy.cem_iterations str]
#                       [--policy.max_std str] [--policy.min_std str] [--policy.n_gaussian_samples str] [--policy.n_pi_samples str]
#                       [--policy.uncertainty_regularizer_coeff str] [--policy.n_elites str] [--policy.elite_weighting_temperature str]
#                       [--policy.gaussian_mean_momentum str] [--policy.max_random_shift_ratio str] [--policy.reward_coeff str]
#                       [--policy.expectile_weight str] [--policy.value_coeff str] [--policy.consistency_coeff str]
#                       [--policy.advantage_scaling str] [--policy.pi_coeff str] [--policy.temporal_decay_coeff str]
#                       [--policy.target_model_momentum str] [--policy.n_action_pred_token str] [--policy.action_chunk_size str]
#                       [--policy.vision_backbone str] [--policy.crop_shape str] [--policy.crop_is_random str]
#                       [--policy.pretrained_backbone_weights str] [--policy.use_group_norm str] [--policy.spatial_softmax_num_keypoints str]
#                       [--policy.n_vqvae_training_steps str] [--policy.vqvae_n_embed str] [--policy.vqvae_embedding_dim str]
#                       [--policy.vqvae_enc_hidden_dim str] [--policy.gpt_block_size str] [--policy.gpt_input_dim str]
#                       [--policy.gpt_output_dim str] [--policy.gpt_n_layer str] [--policy.gpt_n_head str] [--policy.gpt_hidden_dim str]
#                       [--policy.dropout str] [--policy.offset_loss_weight str] [--policy.primary_code_loss_weight str]
#                       [--policy.secondary_code_loss_weight str] [--policy.bet_softmax_temperature str] [--policy.sequentially_select str]
#                       [--policy.optimizer_lr str] [--policy.optimizer_betas str] [--policy.optimizer_eps str]
#                       [--policy.optimizer_weight_decay str] [--policy.optimizer_vqvae_lr str] [--policy.optimizer_vqvae_weight_decay str]
#                       [--policy.scheduler_warmup_steps str] [--policy.dataset_stats str] [--policy.storage_device str]
#                       [--policy.vision_encoder_name str] [--policy.freeze_vision_encoder str] [--policy.image_encoder_hidden_dim str]
#                       [--policy.shared_encoder str] [--policy.num_discrete_actions str] [--policy.online_steps str]
#                       [--policy.online_buffer_capacity str] [--policy.offline_buffer_capacity str] [--policy.async_prefetch str]
#                       [--policy.online_step_before_learning str] [--policy.policy_update_freq str] [--policy.discount str]
#                       [--policy.temperature_init str] [--policy.num_critics str] [--policy.num_subsample_critics str] [--policy.critic_lr str]
#                       [--policy.actor_lr str] [--policy.temperature_lr str] [--policy.critic_target_update_weight str] [--policy.utd_ratio str]
#                       [--policy.state_encoder_hidden_dim str] [--policy.target_entropy str] [--policy.use_backup_entropy str]
#                       [--critic_network_kwargs str] [--policy.critic_network_kwargs.hidden_dims str]
#                       [--policy.critic_network_kwargs.activate_final str] [--policy.critic_network_kwargs.final_activation str]
#                       [--actor_network_kwargs str] [--policy.actor_network_kwargs.hidden_dims str]
#                       [--policy.actor_network_kwargs.activate_final str] [--policy_kwargs str] [--policy.policy_kwargs.use_tanh_squash str]
#                       [--policy.policy_kwargs.std_min str] [--policy.policy_kwargs.std_max str] [--policy.policy_kwargs.init_final str]
#                       [--discrete_critic_network_kwargs str] [--policy.discrete_critic_network_kwargs.hidden_dims str]
#                       [--policy.discrete_critic_network_kwargs.activate_final str]
#                       [--policy.discrete_critic_network_kwargs.final_activation str] [--actor_learner_config str]
#                       [--policy.actor_learner_config.learner_host str] [--policy.actor_learner_config.learner_port str]
#                       [--policy.actor_learner_config.policy_parameters_push_frequency str] [--policy.actor_learner_config.queue_get_timeout str]
#                       [--concurrency str] [--policy.concurrency.actor str] [--policy.concurrency.learner str] [--policy.use_torch_compile str]
#                       [--policy.n_obs_steps str] [--policy.input_features str] [--policy.output_features str] [--policy.device str]
#                       [--policy.use_amp str] [--policy.push_to_hub str] [--policy.repo_id str] [--policy.private str] [--policy.tags str]
#                       [--policy.license str] [--policy.pretrained_path str] [--policy.name str] [--policy.num_classes str]
#                       [--policy.hidden_dim str] [--policy.latent_dim str] [--policy.image_embedding_pooling_dim str] [--policy.dropout_rate str]
#                       [--policy.model_name str] [--policy.model_type str] [--policy.num_cameras str] [--policy.learning_rate str]
#                       [--policy.weight_decay str] [--policy.grad_clip_norm str] [--policy.normalization_mapping str] [--display_data str]
#                       [--play_sounds str] [--resume str]