controller:
  server_address: 115.145.175.11:8080
  environment_dt: 0.0333
  logger_name: lekiwi_vla_executor
  task: "pick green object and put it on the green"
  preset_datasets:
    pick_to_place:
      repo_id: khmin101/poc2_demo2
      episode_index: 0
    place_to_pick:
      repo_id: khmin101/goto_pick_ver1
      episode_index: 0
  policy_config:
    policy_type: act
    pretrained_name_or_path: khmin101/poc2_ver5_pick_100
    actions_per_chunk: 100
    device: cuda
  gripper_open_threshold: 70.0
  gripper_open_duration_s: 0.5
  chunk_size_threshold: 0.2
  aggregate_fn_name: weighted_average
robot:
  remote_ip: 192.168.20.199
  port_zmq_cmd: 5555
  port_zmq_observations: 5556
  id: lekiwi
  cameras:
    # wrist:
    #   type: opencv
    #   index_or_path: /dev/video1
    #   width: 640
    #   height: 480
    #   fps: 30
    front:
      type: opencv
      index_or_path: /dev/video0
      width: 640
      height: 480
      fps: 30
fsm:
  pick_to_place_path: pick_to_place
  place_to_pick_path: place_to_pick
target_hz: 30
auto_start: true
